interface EnumOption {
  title: string;
  id: string;
}

export const GenderEnum: EnumOption[] = [
  { title: 'Male', id: 'Male' },
  { title: 'Female', id: 'Female' },
  { title: 'Other', id: 'Other' },
];

export const BloodGroupEnum: EnumOption[] = [
  { title: 'A+', id: 'A +' },
  { title: 'A-', id: 'A -' },
  { title: 'B+', id: 'B +' },
  { title: 'B-', id: 'B -' },
  { title: 'AB+', id: 'AB +' },
  { title: 'AB-', id: 'AB -' },
  { title: 'O+', id: 'O +' },
  { title: 'O-', id: 'O -' },
];

export const ConsultEnum: EnumOption[] = [
  { title: '6 AM - 2 PM (Morning)', id: '6 AM - 2 PM (Morning)' },
  { title: '2 PM - 10 PM (Afternoon)', id: '3 PM - 10 PM (Afternoon)' },
  { title: '10 PM - 6 AM (Night)', id: '11 PM - 6 AM (Night)' },
];

export const OngoingTreatmentEnum: EnumOption[] = [
  { title: 'Yes', id: 'Yes' },
  { title: 'No', id: 'No' },
];

export const MedicalConditionsEnum: EnumOption[] = [
  { title: 'Common Illnesses', id: 'Common illnesses' },
  { title: 'Minor Injuries', id: 'Minor injuries' },
  { title: 'Routine Check-ups', id: 'Routine check-ups' },
  { title: 'Vaccinations', id: 'Vaccinations' },
  { title: 'Preventive Care', id: 'Preventive care' },

  { title: 'Heart Pain', id: 'Heart pain' },
  { title: 'Hypertension', id: 'Hypertension' },

  { title: 'Growth Disorders', id: 'Growth disorders' },
  { title: 'Infections', id: 'Infections' },
  { title: 'Childhood Illnesses', id: 'Childhood illnesses' },

  { title: 'Fractures', id: 'Fractures' },
  { title: 'Arthritis', id: 'Arthritis' },
  { title: 'Sports Injuries', id: 'Sports injuries' },
  { title: 'Spinal Deformities', id: 'Spinal deformities' },

  { title: 'Menstrual Issues', id: 'Menstrual issues' },
  { title: 'Pelvic Pain', id: 'Pelvic pain' },
  { title: 'Ovarian Cysts', id: 'Ovarian cysts' },

  { title: 'Prenatal Care', id: 'Prenatal care' },
  { title: 'Pregnancy', id: 'Pregnancy' },
  { title: 'Childbirth', id: 'Childbirth' },
  { title: 'Postpartum Care', id: 'Postpartum care' },

  { title: 'Skin Problems', id: 'Skin Problems' },
  { title: 'Hair Problems', id: 'Hair Problems' },
  { title: 'Nail Problems', id: 'Nail Problems' },

  { title: 'Diabetes', id: 'Diabetes' },
  { title: 'Thyroid Disorders', id: 'Thyroid disorders' },
  { title: 'Adrenal Gland Issues', id: 'Adrenal gland issues' },

  { title: 'Brain Pain', id: 'Brain pain' },
  { title: 'Spinal Cord Pain', id: 'Spinal cord pain' },
  { title: 'Nerves Pain', id: 'Nerves pain' },

  { title: 'Depression', id: 'Depression' },
  { title: 'Anxiety', id: 'Anxiety' },
  { title: 'Schizophrenia', id: 'Schizophrenia' },
  { title: 'Bipolar Disorder', id: 'Bipolar disorder' },

  { title: 'IBS', id: 'IBS' },
  { title: 'Ulcers', id: 'Ulcers' },
  { title: 'Crohn\'s Disease', id: 'Crohn\'s Disease' },
  { title: 'Liver Disorders', id: 'Liver disorders' },

  { title: 'Asthma', id: 'Asthma' },
  { title: 'COPD', id: 'COPD' },
  { title: 'Pneumonia', id: 'Pneumonia' },

  { title: 'Breast Cancer', id: 'Breast cancer' },
  { title: 'Lung Cancer', id: 'Lung cancer' },
  { title: 'Leukemia', id: 'Leukemia' },
  { title: 'Lymphoma', id: 'Lymphoma' },

  { title: 'Eye Disorders', id: 'Eye disorders' },

  { title: 'Kidney Stones', id: 'Kidney stones' },
  { title: 'Prostate Issues', id: 'Prostate issues' },
];

export const HeightEnum: EnumOption[] = [
  { title: '1.0 Ft', id: '1.0 Ft' },
  { title: '1.1 Ft', id: '1.1 Ft' },
  { title: '1.2 Ft', id: '1.2 Ft' },
  { title: '1.3 Ft', id: '1.3 Ft' },
  { title: '1.4 Ft', id: '1.4 Ft' },
  { title: '1.5 Ft', id: '1.5 Ft' },
  { title: '1.6 Ft', id: '1.6 Ft' },
  { title: '1.7 Ft', id: '1.7 Ft' },
  { title: '1.8 Ft', id: '1.8 Ft' },
  { title: '1.9 Ft', id: '1.9 Ft' },
  { title: '2.0 Ft', id: '2.0 Ft' },
  { title: '2.1 Ft', id: '2.1 Ft' },
  { title: '2.2 Ft', id: '2.2 Ft' },
  { title: '2.3 Ft', id: '2.3 Ft' },
  { title: '2.4 Ft', id: '2.4 Ft' },
  { title: '2.5 Ft', id: '2.5 Ft' },
  { title: '2.6 Ft', id: '2.6 Ft' },
  { title: '2.7 Ft', id: '2.7 Ft' },
  { title: '2.8 Ft', id: '2.8 Ft' },
  { title: '2.9 Ft', id: '2.9 Ft' },
  { title: '3.0 Ft', id: '3.0 Ft' },
  { title: '3.1 Ft', id: '3.1 Ft' },
  { title: '3.2 Ft', id: '3.2 Ft' },
  { title: '3.3 Ft', id: '3.3 Ft' },
  { title: '3.4 Ft', id: '3.4 Ft' },
  { title: '3.5 Ft', id: '3.5 Ft' },
  { title: '3.6 Ft', id: '3.6 Ft' },
  { title: '3.7 Ft', id: '3.7 Ft' },
  { title: '3.8 Ft', id: '3.8 Ft' },
  { title: '3.9 Ft', id: '3.9 Ft' },
  { title: '4.0 Ft', id: '4.0 Ft' },
  { title: '4.1 Ft', id: '4.1 Ft' },
  { title: '4.2 Ft', id: '4.2 Ft' },
  { title: '4.3 Ft', id: '4.3 Ft' },
  { title: '4.4 Ft', id: '4.4 Ft' },
  { title: '4.5 Ft', id: '4.5 Ft' },
  { title: '4.6 Ft', id: '4.6 Ft' },
  { title: '4.7 Ft', id: '4.7 Ft' },
  { title: '4.8 Ft', id: '4.8 Ft' },
  { title: '4.9 Ft', id: '4.9 Ft' },
  { title: '5.0 Ft', id: '5.0 Ft' },
  { title: '5.1 Ft', id: '5.1 Ft' },
  { title: '5.2 Ft', id: '5.2 Ft' },
  { title: '5.3 Ft', id: '5.3 Ft' },
  { title: '5.4 Ft', id: '5.4 Ft' },
  { title: '5.5 Ft', id: '5.5 Ft' },
  { title: '5.6 Ft', id: '5.6 Ft' },
  { title: '5.7 Ft', id: '5.7 Ft' },
  { title: '5.8 Ft', id: '5.8 Ft' },
  { title: '5.9 Ft', id: '5.9 Ft' },
  { title: '6.0 Ft', id: '6.0 Ft' },
  { title: '6.1 Ft', id: '6.1 Ft' },
  { title: '6.2 Ft', id: '6.2 Ft' },
  { title: '6.3 Ft', id: '6.3 Ft' },
  { title: '6.4 Ft', id: '6.4 Ft' },
  { title: '6.5 Ft', id: '6.5 Ft' },
  { title: '6.6 Ft', id: '6.6 Ft' },
  { title: '6.7 Ft', id: '6.7 Ft' },
  { title: '6.8 Ft', id: '6.8 Ft' },
  { title: '6.9 Ft', id: '6.9 Ft' },
  { title: '7.0 Ft', id: '7.0 Ft' },
  { title: '7.1 Ft', id: '7.1 Ft' },
  { title: '7.2 Ft', id: '7.2 Ft' },
  { title: '7.3 Ft', id: '7.3 Ft' },
  { title: '7.4 Ft', id: '7.4 Ft' },
  { title: '7.5 Ft', id: '7.5 Ft' },
  { title: '7.6 Ft', id: '7.6 Ft' },
  { title: '7.7 Ft', id: '7.7 Ft' },
  { title: '7.8 Ft', id: '7.8 Ft' },
  { title: '7.9 Ft', id: '7.9 Ft' },
  { title: '8.0 Ft', id: '8.0 Ft' },
  { title: '8.1 Ft', id: '8.1 Ft' },
  { title: '8.2 Ft', id: '8.2 Ft' },
  { title: '8.3 Ft', id: '8.3 Ft' },
  { title: '8.4 Ft', id: '8.4 Ft' },
  { title: '8.5 Ft', id: '8.5 Ft' },
  { title: '8.6 Ft', id: '8.6 Ft' },
  { title: '8.7 Ft', id: '8.7 Ft' },
  { title: '8.8 Ft', id: '8.8 Ft' },
  { title: '8.9 Ft', id: '8.9 Ft' },
  { title: '9.0 Ft', id: '9.0 Ft' },
];

export const WeightEnum: EnumOption[] = [
  { title: 'Below 5kg', id: 'Below 5Kg' },
  { title: '5 Kg', id: '5 Kg' },
  { title: '6 Kg', id: '6 Kg' },
  { title: '7 Kg', id: '7 Kg' },
  { title: '8 Kg', id: '8 Kg' },
  { title: '9 Kg', id: '9 Kg' },
  { title: '10 Kg', id: '10 Kg' },
  { title: '11 Kg', id: '11 Kg' },
  { title: '12 Kg', id: '12 Kg' },
  { title: '13 Kg', id: '13 Kg' },
  { title: '14 Kg', id: '14 Kg' },
  { title: '15 Kg', id: '15 Kg' },
  { title: '16 Kg', id: '16 Kg' },
  { title: '17 Kg', id: '17 Kg' },
  { title: '18 Kg', id: '18 Kg' },
  { title: '19 Kg', id: '19 Kg' },
  { title: '20 Kg', id: '20 Kg' },
  { title: '21 Kg', id: '21 Kg' },
  { title: '22 Kg', id: '22 Kg' },
  { title: '23 Kg', id: '23 Kg' },
  { title: '24 Kg', id: '24 Kg' },
  { title: '25 Kg', id: '25 Kg' },
  { title: '26 Kg', id: '26 Kg' },
  { title: '27 Kg', id: '27 Kg' },
  { title: '28 Kg', id: '28 Kg' },
  { title: '29 Kg', id: '29 Kg' },
  { title: '30 Kg', id: '30 Kg' },
  { title: '31 Kg', id: '31 Kg' },
  { title: '32 Kg', id: '32 Kg' },
  { title: '33 Kg', id: '33 Kg' },
  { title: '34 Kg', id: '34 Kg' },
  { title: '35 Kg', id: '35 Kg' },
  { title: '36 Kg', id: '36 Kg' },
  { title: '37 Kg', id: '37 Kg' },
  { title: '38 Kg', id: '38 Kg' },
  { title: '39 Kg', id: '39 Kg' },
  { title: '40 Kg', id: '40 Kg' },
  { title: '41 Kg', id: '41 Kg' },
  { title: '42 Kg', id: '42 Kg' },
  { title: '43 Kg', id: '43 Kg' },
  { title: '44 Kg', id: '44 Kg' },
  { title: '45 Kg', id: '45 Kg' },
  { title: '46 Kg', id: '46 Kg' },
  { title: '47 Kg', id: '47 Kg' },
  { title: '48 Kg', id: '48 Kg' },
  { title: '49 Kg', id: '49 Kg' },
  { title: '50 Kg', id: '50 Kg' },
  { title: '51 Kg', id: '51 Kg' },
  { title: '52 Kg', id: '52 Kg' },
  { title: '53 Kg', id: '53 Kg' },
  { title: '54 Kg', id: '54 Kg' },
  { title: '55 Kg', id: '55 Kg' },
  { title: '56 Kg', id: '56 Kg' },
  { title: '57 Kg', id: '57 Kg' },
  { title: '58 Kg', id: '58 Kg' },
  { title: '59 Kg', id: '59 Kg' },
  { title: '60 Kg', id: '60 Kg' },
  { title: '61 Kg', id: '61 Kg' },
  { title: '62 Kg', id: '62 Kg' },
  { title: '63 Kg', id: '63 Kg' },
  { title: '64 Kg', id: '64 Kg' },
  { title: '65 Kg', id: '65 Kg' },
  { title: '66 Kg', id: '66 Kg' },
  { title: '67 Kg', id: '67 Kg' },
  { title: '68 Kg', id: '68 Kg' },
  { title: '69 Kg', id: '69 Kg' },
  { title: '70 Kg', id: '70 Kg' },
  { title: '71 Kg', id: '71 Kg' },
  { title: '72 Kg', id: '72 Kg' },
  { title: '73 Kg', id: '73 Kg' },
  { title: '74 Kg', id: '74 Kg' },
  { title: '75 Kg', id: '75 Kg' },
  { title: '76 Kg', id: '76 Kg' },
  { title: '77 Kg', id: '77 Kg' },
  { title: '78 Kg', id: '78 Kg' },
  { title: '79 Kg', id: '79 Kg' },
  { title: '80 Kg', id: '80 Kg' },
  { title: '81 Kg', id: '81 Kg' },
  { title: '82 Kg', id: '82 Kg' },
  { title: '83 Kg', id: '83 Kg' },
  { title: '84 Kg', id: '84 Kg' },
  { title: '85 Kg', id: '85 Kg' },
  { title: '86 Kg', id: '86 Kg' },
  { title: '87 Kg', id: '87 Kg' },
  { title: '88 Kg', id: '88 Kg' },
  { title: '89 Kg', id: '89 Kg' },
  { title: '90 Kg', id: '90 Kg' },
  { title: '91 Kg', id: '91 Kg' },
  { title: '92 Kg', id: '92 Kg' },
  { title: '93 Kg', id: '93 Kg' },
  { title: '94 Kg', id: '94 Kg' },
  { title: '95 Kg', id: '95 Kg' },
  { title: '96 Kg', id: '96 Kg' },
  { title: '97 Kg', id: '97 Kg' },
  { title: '98 Kg', id: '98 Kg' },
  { title: '99 Kg', id: '99 Kg' },
  { title: '100 Kg', id: '100 Kg' },
  { title: 'Above 100 Kg', id: 'Above 100 Kg' },
];
