export const GenderEnum = [
  { label: 'Male', value: 'Male' },
  { label: 'Female', value: 'Female' },
  { label: 'Other', value: 'Other' },
];

export const BloodGroupEnum = [
  { label: 'A+', value: 'A +' },
  { label: 'A-', value: 'A -' },
  { label: 'B+', value: 'B +' },
  { label: 'B-', value: 'B -' },
  { label: 'AB+', value: 'AB +' },
  { label: 'AB-', value: 'AB -' },
  { label: 'O+', value: 'O +' },
  { label: 'O-', value: 'O -' },
];

export const ConsultEnum = [
    { label: '6 AM - 2 PM (Morning)', value: '6 AM - 2 PM (Morning)' },
    { label: '3 PM - 10 PM (Afternoon)', value: '3 PM - 10 PM (Afternoon)' },
    { label: '11 PM - 6 AM (Night)', value: '11 PM - 6 AM (Night)' },
  ];
  

export const OngoingTreatmentEnum = [
  { label: 'Yes', value: 'Yes' },
  { label: 'No', value: 'No' },
];


export const MedicalConditionsEnum = [
    { label: 'Common Illnesses', value: 'Common illnesses' },
    { label: 'Minor Injuries', value: 'Minor injuries' },
    { label: 'Routine Check-ups', value: 'Routine check-ups' },
    { label: 'Vaccinations', value: 'Vaccinations' },
    { label: 'Preventive Care', value: 'Preventive care' },
  
    { label: 'Heart Pain', value: 'Heart pain' },
    { label: 'Hypertension', value: 'Hypertension' },
  
    { label: 'Growth Disorders', value: 'Growth disorders' },
    { label: 'Infections', value: 'Infections' },
    { label: 'Childhood Illnesses', value: 'Childhood illnesses' },
  
    { label: 'Fractures', value: 'Fractures' },
    { label: 'Arthritis', value: 'Arthritis' },
    { label: 'Sports Injuries', value: 'Sports injuries' },
    { label: 'Spinal Deformities', value: 'Spinal deformities' },
  
    { label: 'Menstrual Issues', value: 'Menstrual issues' },
    { label: 'Pelvic Pain', value: 'Pelvic pain' },
    { label: 'Ovarian Cysts', value: 'Ovarian cysts' },
  
    { label: 'Prenatal Care', value: 'Prenatal care' },
    { label: 'Pregnancy', value: 'Pregnancy' },
    { label: 'Childbirth', value: 'Childbirth' },
    { label: 'Postpartum Care', value: 'Postpartum care' },
  
    { label: 'Skin Problems', value: 'Skin Problems' },
    { label: 'Hair Problems', value: 'Hair Problems' },
    { label: 'Nail Problems', value: 'Nail Problems' },
  
    { label: 'Diabetes', value: 'Diabetes' },
    { label: 'Thyroid Disorders', value: 'Thyroid disorders' },
    { label: 'Adrenal Gland Issues', value: 'Adrenal gland issues' },
  
    { label: 'Brain Pain', value: 'Brain pain' },
    { label: 'Spinal Cord Pain', value: 'Spinal cord pain' },
    { label: 'Nerves Pain', value: 'Nerves pain' },
  
    { label: 'Depression', value: 'Depression' },
    { label: 'Anxiety', value: 'Anxiety' },
    { label: 'Schizophrenia', value: 'Schizophrenia' },
    { label: 'Bipolar Disorder', value: 'Bipolar disorder' },
  
    { label: 'IBS', value: 'IBS' },
    { label: 'Ulcers', value: 'Ulcers' },
    { label: 'Crohn’s Disease', value: 'Crohn’s Disease' },
    { label: 'Liver Disorders', value: 'Liver disorders' },
  
    { label: 'Asthma', value: 'Asthma' },
    { label: 'COPD', value: 'COPD' },
    { label: 'Pneumonia', value: 'Pneumonia' },
  
    { label: 'Breast Cancer', value: 'Breast cancer' },
    { label: 'Lung Cancer', value: 'Lung cancer' },
    { label: 'Leukemia', value: 'Leukemia' },
    { label: 'Lymphoma', value: 'Lymphoma' },
  
    { label: 'Eye Disorders', value: 'Eye disorders' },
  
    { label: 'Kidney Stones', value: 'Kidney stones' },
    { label: 'Prostate Issues', value: 'Prostate issues' },
  ];
  

  export const HeightEnum = [
    { label: '1.0 Ft', value: '1.0 Ft' },
    { label: '1.1 Ft', value: '1.1 Ft' },
    { label: '1.2 Ft', value: '1.2 Ft' },
    { label: '1.3 Ft', value: '1.3 Ft' },
    { label: '1.4 Ft', value: '1.4 Ft' },
    { label: '1.5 Ft', value: '1.5 Ft' },
    { label: '1.6 Ft', value: '1.6 Ft' },
    { label: '1.7 Ft', value: '1.7 Ft' },
    { label: '1.8 Ft', value: '1.8 Ft' },
    { label: '1.9 Ft', value: '1.9 Ft' },
    { label: '2.0 Ft', value: '2.0 Ft' },
    { label: '2.1 Ft', value: '2.1 Ft' },
    { label: '2.2 Ft', value: '2.2 Ft' },
    { label: '2.3 Ft', value: '2.3 Ft' },
    { label: '2.4 Ft', value: '2.4 Ft' },
    { label: '2.5 Ft', value: '2.5 Ft' },
    { label: '2.6 Ft', value: '2.6 Ft' },
    { label: '2.7 Ft', value: '2.7 Ft' },
    { label: '2.8 Ft', value: '2.8 Ft' },
    { label: '2.9 Ft', value: '2.9 Ft' },
    { label: '3.0 Ft', value: '3.0 Ft' },
    { label: '3.1 Ft', value: '3.1 Ft' },
    { label: '3.2 Ft', value: '3.2 Ft' },
    { label: '3.3 Ft', value: '3.3 Ft' },
    { label: '3.4 Ft', value: '3.4 Ft' },
    { label: '3.5 Ft', value: '3.5 Ft' },
    { label: '3.6 Ft', value: '3.6 Ft' },
    { label: '3.7 Ft', value: '3.7 Ft' },
    { label: '3.8 Ft', value: '3.8 Ft' },
    { label: '3.9 Ft', value: '3.9 Ft' },
    { label: '4.0 Ft', value: '4.0 Ft' },
    { label: '4.1 Ft', value: '4.1 Ft' },
    { label: '4.2 Ft', value: '4.2 Ft' },
    { label: '4.3 Ft', value: '4.3 Ft' },
    { label: '4.4 Ft', value: '4.4 Ft' },
    { label: '4.5 Ft', value: '4.5 Ft' },
    { label: '4.6 Ft', value: '4.6 Ft' },
    { label: '4.7 Ft', value: '4.7 Ft' },
    { label: '4.8 Ft', value: '4.8 Ft' },
    { label: '4.9 Ft', value: '4.9 Ft' },
    { label: '5.0 Ft', value: '5.0 Ft' },
    { label: '5.1 Ft', value: '5.1 Ft' },
    { label: '5.2 Ft', value: '5.2 Ft' },
    { label: '5.3 Ft', value: '5.3 Ft' },
    { label: '5.4 Ft', value: '5.4 Ft' },
    { label: '5.5 Ft', value: '5.5 Ft' },
    { label: '5.6 Ft', value: '5.6 Ft' },
    { label: '5.7 Ft', value: '5.7 Ft' },
    { label: '5.8 Ft', value: '5.8 Ft' },
    { label: '5.9 Ft', value: '5.9 Ft' },
    { label: '6.0 Ft', value: '6.0 Ft' },
    { label: '6.1 Ft', value: '6.1 Ft' },
    { label: '6.2 Ft', value: '6.2 Ft' },
    { label: '6.3 Ft', value: '6.3 Ft' },
    { label: '6.4 Ft', value: '6.4 Ft' },
    { label: '6.5 Ft', value: '6.5 Ft' },
    { label: '6.6 Ft', value: '6.6 Ft' },
    { label: '6.7 Ft', value: '6.7 Ft' },
    { label: '6.8 Ft', value: '6.8 Ft' },
    { label: '6.9 Ft', value: '6.9 Ft' },
    { label: '7.0 Ft', value: '7.0 Ft' },
    { label: '7.1 Ft', value: '7.1 Ft' },
    { label: '7.2 Ft', value: '7.2 Ft' },
    { label: '7.3 Ft', value: '7.3 Ft' },
    { label: '7.4 Ft', value: '7.4 Ft' },
    { label: '7.5 Ft', value: '7.5 Ft' },
    { label: '7.6 Ft', value: '7.6 Ft' },
    { label: '7.7 Ft', value: '7.7 Ft' },
    { label: '7.8 Ft', value: '7.8 Ft' },
    { label: '7.9 Ft', value: '7.9 Ft' },
    { label: '8.0 Ft', value: '8.0 Ft' },
    { label: '8.1 Ft', value: '8.1 Ft' },
    { label: '8.2 Ft', value: '8.2 Ft' },
    { label: '8.3 Ft', value: '8.3 Ft' },
    { label: '8.4 Ft', value: '8.4 Ft' },
    { label: '8.5 Ft', value: '8.5 Ft' },
    { label: '8.6 Ft', value: '8.6 Ft' },
    { label: '8.7 Ft', value: '8.7 Ft' },
    { label: '8.8 Ft', value: '8.8 Ft' },
    { label: '8.9 Ft', value: '8.9 Ft' },
    { label: '9.0 Ft', value: '9.0 Ft' }
  ]
  
  export const WeightEnum =[
    
        { label: 'Below 5kg', value: 'Below 5Kg' },
        { label: '5 Kg', value: '5 Kg' },
        { label: '6 Kg', value: '6 Kg' },
        { label: '7 Kg', value: '7 Kg' },
        { label: '8 Kg', value: '8 Kg' },
        { label: '9 Kg', value: '9 Kg' },
        { label: '10 Kg', value: '10 Kg' },
        { label: '11 Kg', value: '11 Kg' },
        { label: '12 Kg', value: '12 Kg' },
        { label: '13 Kg', value: '13 Kg' },
        { label: '14 Kg', value: '14 Kg' },
        { label: '15 Kg', value: '15 Kg' },
        { label: '16 Kg', value: '16 Kg' },
        { label: '17 Kg', value: '17 Kg' },
        { label: '18 Kg', value: '18 Kg' },
        { label: '19 Kg', value: '19 Kg' },
        { label: '20 Kg', value: '20 Kg' },
        { label: '21 Kg', value: '21 Kg' },
        { label: '22 Kg', value: '22 Kg' },
        { label: '23 Kg', value: '23 Kg' },
        { label: '24 Kg', value: '24 Kg' },
        { label: '25 Kg', value: '25 Kg' },
        { label: '26 Kg', value: '26 Kg' },
        { label: '27 Kg', value: '27 Kg' },
        { label: '28 Kg', value: '28 Kg' },
        { label: '29 Kg', value: '29 Kg' },
        { label: '30 Kg', value: '30 Kg' },
        { label: '31 Kg', value: '31 Kg' },
        { label: '32 Kg', value: '32 Kg' },
        { label: '33 Kg', value: '33 Kg' },
        { label: '34 Kg', value: '34 Kg' },
        { label: '35 Kg', value: '35 Kg' },
        { label: '36 Kg', value: '36 Kg' },
        { label: '37 Kg', value: '37 Kg' },
        { label: '38 Kg', value: '38 Kg' },
        { label: '39 Kg', value: '39 Kg' },
        { label: '40 Kg', value: '40 Kg' },
        { label: '41 Kg', value: '41 Kg' },
        { label: '42 Kg', value: '42 Kg' },
        { label: '43 Kg', value: '43 Kg' },
        { label: '44 Kg', value: '44 Kg' },
        { label: '45 Kg', value: '45 Kg' },
        { label: '46 Kg', value: '46 Kg' },
        { label: '47 Kg', value: '47 Kg' },
        { label: '48 Kg', value: '48 Kg' },
        { label: '49 Kg', value: '49 Kg' },
        { label: '50 Kg', value: '50 Kg' },
        { label: '51 Kg', value: '51 Kg' },
        { label: '52 Kg', value: '52 Kg' },
        { label: '53 Kg', value: '53 Kg' },
        { label: '54 Kg', value: '54 Kg' },
        { label: '55 Kg', value: '55 Kg' },
        { label: '56 Kg', value: '56 Kg' },
        { label: '57 Kg', value: '57 Kg' },
        { label: '58 Kg', value: '58 Kg' },
        { label: '59 Kg', value: '59 Kg' },
        { label: '60 Kg', value: '60 Kg' },
        { label: '61 Kg', value: '61 Kg' },
        { label: '62 Kg', value: '62 Kg' },
        { label: '63 Kg', value: '63 Kg' },
        { label: '64 Kg', value: '64 Kg' },
        { label: '65 Kg', value: '65 Kg' },
        { label: '66 Kg', value: '66 Kg' },
        { label: '67 Kg', value: '67 Kg' },
        { label: '68 Kg', value: '68 Kg' },
        { label: '69 Kg', value: '69 Kg' },
        { label: '70 Kg', value: '70 Kg' },
        { label: '71 Kg', value: '71 Kg' },
        { label: '72 Kg', value: '72 Kg' },
        { label: '73 Kg', value: '73 Kg' },
        { label: '74 Kg', value: '74 Kg' },
        { label: '75 Kg', value: '75 Kg' },
        { label: '76 Kg', value: '76 Kg' },
        { label: '77 Kg', value: '77 Kg' },
        { label: '78 Kg', value: '78 Kg' },
        { label: '79 Kg', value: '79 Kg' },
        { label: '80 Kg', value: '80 Kg' },
        { label: '81 Kg', value: '81 Kg' },
        { label: '82 Kg', value: '82 Kg' },
        { label: '83 Kg', value: '83 Kg' },
        { label: '84 Kg', value: '84 Kg' },
        { label: '85 Kg', value: '85 Kg' },
        { label: '86 Kg', value: '86 Kg' },
        { label: '87 Kg', value: '87 Kg' },
        { label: '88 Kg', value: '88 Kg' },
        { label: '89 Kg', value: '89 Kg' },
        { label: '90 Kg', value: '90 Kg' },
        { label: '91 Kg', value: '91 Kg' },
        { label: '92 Kg', value: '92 Kg' },
        { label: '93 Kg', value: '93 Kg' },
        { label: '94 Kg', value: '94 Kg' },
        { label: '95 Kg', value: '95 Kg' },
        { label: '96 Kg', value: '96 Kg' },
        { label: '97 Kg', value: '97 Kg' },
        { label: '98 Kg', value: '98 Kg' },
        { label: '99 Kg', value: '99 Kg' },
        { label: '100 Kg', value: '100 Kg' },
        { label: '101 Kg', value: '101 Kg' },
        { label: '102 Kg', value: '102 Kg' },
        { label: '103 Kg', value: '103 Kg' },
        { label: '104 Kg', value: '104 Kg' },
        { label: '105 Kg', value: '105 Kg' },
        { label: '106 Kg', value: '106 Kg' },
        { label: '107 Kg', value: '107 Kg' },
        { label: '108 Kg', value: '108 Kg' },
        { label: '109 Kg', value: '109 Kg' },
        { label: '110 Kg', value: '110 Kg' },
        { label: '111 Kg', value: '111 Kg' },
        { label: '112 Kg', value: '112 Kg' },
        { label: '113 Kg', value: '113 Kg' },
        { label: '114 Kg', value: '114 Kg' },
        { label: '115 Kg', value: '115 Kg' },
        { label: '116 Kg', value: '116 Kg' },
        { label: '117 Kg', value: '117 Kg' },
        { label: '118 Kg', value: '118 Kg' },
        { label: '119 Kg', value: '119 Kg' },
        { label: '120 Kg', value: '120 Kg' },
        { label: '121 Kg', value: '121 Kg' },
        { label: '122 Kg', value: '122 Kg' },
        { label: '123 Kg', value: '123 Kg' },
        { label: '124 Kg', value: '124 Kg' },
        { label: '125 Kg', value: '125 Kg' },
        { label: '126 Kg', value: '126 Kg' },
        { label: '127 Kg', value: '127 Kg' },
        { label: '128 Kg', value: '128 Kg' },
        { label: '129 Kg', value: '129 Kg' },
        { label: '130 Kg', value: '130 Kg' },
        { label: '131 Kg', value: '131 Kg' },
        { label: '132 Kg', value: '132 Kg' },
        { label: '133 Kg', value: '133 Kg' },
        { label: '134 Kg', value: '134 Kg' },
        { label: '135 Kg', value: '135 Kg' },
        { label: '136 Kg', value: '136 Kg' },
        { label: '137 Kg', value: '137 Kg' },
        { label: '138 Kg', value: '138 Kg' },
        { label: '139 Kg', value: '139 Kg' },
        { label: '140 Kg', value: '140 Kg' },
        { label: '141 Kg', value: '141 Kg' },
        { label: '142 Kg', value: '142 Kg' },
        { label: '143 Kg', value: '143 Kg' },
        { label: '144 Kg', value: '144 Kg' },
        { label: '145 Kg', value: '145 Kg' },
        { label: '146 Kg', value: '146 Kg' },
        { label: '147 Kg', value: '147 Kg' },
        { label: '148 Kg', value: '148 Kg' },
        { label: '149 Kg', value: '149 Kg' },
        { label: '150 Kg', value: '150 Kg' },
        { label: 'Above 150 Kg', value: ' Above 150 Kg' },
      ]
      
  